spring.datasource.url=jdbc:mysql://localhost:3306/solocar_db
spring.datasource.username=root
spring.datasource.password=Vera0405..
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
server.port=8080
spring.application.name=solocar-api